# version: '3.8'
# DELETE CACHE docker builder prune

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_8_0_container
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      # FOR DIFFERENT USER --> MYSQL_USER: $MYSQLDB_USER
      # FOR DIFFERENT PASSWORD -->  MYSQL_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 40

  app:
    container_name: node_app
    env_file: ./.env
    build: .
    depends_on:
      mysqldb:
        condition: service_healthy
    links:
      - mysqldb
    ports:
      - $DOCKER_PORT:$PORT
